/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package net.mamian.apiengine.apienginesample.thrift;


/**
 * thrift接口-test
 *
 * @author zhaobeishu
 * */
public class ThriftApiService {

    public interface Iface {

        /**
         * @apiDefine Exception
         *
         * @apiError UserNotFound The id of the User was not found.
         *
         * @apiErrorExample Error-Response:
         *     HTTP/1.1 404 Not Found
         *     {
         *       "error": "UserNotFound"
         *     }
         */

        /**
         * @api {thrift} ThriftApiService.method1 方法1实现的功能
         * @apiName 方法1name
         * @apiGroup ThriftApiService
         *
         * @apiParam {Object} obj 参数1
         *
         * @apiSuccess {Object} Object 方法执行成功后返回的数据
         *
         * @apiSuccessExample Object
         *     {
         *       "result": true,
         *       "code": 1,
         *       "msg":"成功的数据"
         *     }
         * @apiVersion 1.0.0
         */
        public Object method1(Object obj);

    }

}
